= CSCI C490 Design Document Requirements

= Social Clicker

== Section 1 – Motivation for App

I chose to create an idle clicker app because it is a type of app I enjoy while also seeming simple and attainable to create. The target user base is people with a busy schedule who also like to game. The inspiration from the app stems from apps such as AdVenture Capitalist (https://www.kongregate.com/games/HyperHippoGames/adventure-capitalist). The app is available on ios, google play, and steam.

== Section 2 - Requirements

The different screens of my app will include the main game screen where the user can click on different social media collectors to earn followers. Then, there will be a screen where the user can "prestige" and reset their main game to earn points toward upgrades to their collectors. A view model will be used to persist what amount of followers the users has generated as well as upgrades to the collectors upon rotation. Data will also be saved between the views in a similar manner.

The data will be stored locally on the device using a database. The database will be called to retrieve the users followers, level of the collectors, and upgrades on startup of the app. Then, anytime the user upgrades the level of a collector, the same data is saved to the database. Finally, the data is saved before destroy of the app, when they are closing out.

My app wil connect to the internet by having the ability to click on any of the social media collectors, and select "learn more". Doing so will take the user to the webpage/app of that social media platform in order for them to do more research about the platform.

=== 2.1 User Interface

5. You must submit diagrams for all the different screens in your app (both portrait and landscape configurations),
one diagram per screen. These diagrams must clearly show the layout of your app's screens, i.e., where images, menus, widgets, views, etc., appear. These can be hand drawn with a .png submitted of the drawing.

== Section 3 – MVC Breakdown
=== 3.1 View

create view on paper

=== 3.2 Model

There will need to be data for the total amount of followers the player has. Then each platform will be a class object with data such as level and a timer to track when it generates a follower. Upgrades will also be tracked. Methods needed would include, level up platform, increment followers, and set upgrade.

The database used will need a table for platforms, with columns such as level and timer setting. Then a table will be needed to track upgrades which will have a column of checkbox to enable the upgrade. Finally, a player table will track how many followers a user has and the prestige points a user has to go toward upgrades.

=== 3.3 Controller

